/*每一个异常部分 都写一个try catch 是比较麻烦的
 * 假设： 这多个问题 我们就想出现一个就不让在继续走下一个有问题的地方
 * 怎么解决呢？ 把多个有问题的代码用一个try处理即可
 * 异常处理变形： try{
 * 
 * 			}catch(){
 * 
 * 			}catch(){
 * 
 * 			}
 * 
 * */
package 异常;

public class ExceptionDemo3 {
	public static void main(String[] args) {
		int a=10;
		int b=0;
		
		
		int[] arr={1,2,3};
		
		
		try {
			System.out.println(arr[3]);
			System.out.println(a/b);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("数组越界异常");
		}catch (ArithmeticException e) {
			System.out.println("除数不能是0");
		}
		
		
		
		System.out.println("over");

	}

}
